### ISSUE TITLE
Try to stop the screen sleeping in timer mode

### ISSUE THREAD

**Issue by freshteapot** [freshteapot/the_humble_plank#10]
# Problem

> the countdown is not seen as an active screen so if I do not tap the screen it goes to "sleep" after a minute

- Bubbled up on android

# How to recreate
- Set "Screen timeout" in Android to 15 seconds.
- Start a plank.
- After 15 seconds the screen goes black

# Todo
- [x] Works on Android
- [ ] Works on iOS

**Comment by pjsamuel3** [comment]
https://stackoverflow.com/questions/51846104/flutter-deactivate-screen-timeout

**Comment by freshteapot** [comment]
@pjsamuel3 thanks for the tip. I was sold until I saw that the github repo is stale. But it spurred me onto find

https://pub.dev/packages/wakelock/install

which at least today is actively maintained.
